/*
 * This file is generated by jOOQ.
 */
package com.libertest.generatedsources.entity.tables;


import com.libertest.generatedsources.entity.DefaultSchema;
import com.libertest.generatedsources.entity.Indexes;
import com.libertest.generatedsources.entity.Keys;
import com.libertest.generatedsources.entity.tables.records.IngredientesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ingredientes extends TableImpl<IngredientesRecord> {

    private static final long serialVersionUID = 385468775;

    /**
     * The reference instance of <code>ingredientes</code>
     */
    public static final Ingredientes INGREDIENTES = new Ingredientes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IngredientesRecord> getRecordType() {
        return IngredientesRecord.class;
    }

    /**
     * The column <code>ingredientes.ID</code>.
     */
    public final TableField<IngredientesRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ingredientes.NOME_RECEITA</code>.
     */
    public final TableField<IngredientesRecord, String> NOME_RECEITA = createField("NOME_RECEITA", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>ingredientes.INGREDIENTE</code>.
     */
    public final TableField<IngredientesRecord, String> INGREDIENTE = createField("INGREDIENTE", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>ingredientes</code> table reference
     */
    public Ingredientes() {
        this(DSL.name("ingredientes"), null);
    }

    /**
     * Create an aliased <code>ingredientes</code> table reference
     */
    public Ingredientes(String alias) {
        this(DSL.name(alias), INGREDIENTES);
    }

    /**
     * Create an aliased <code>ingredientes</code> table reference
     */
    public Ingredientes(Name alias) {
        this(alias, INGREDIENTES);
    }

    private Ingredientes(Name alias, Table<IngredientesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ingredientes(Name alias, Table<IngredientesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Ingredientes(Table<O> child, ForeignKey<O, IngredientesRecord> key) {
        super(child, key, INGREDIENTES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INGREDIENTES_FK_ING_RECEITA, Indexes.INGREDIENTES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IngredientesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_INGREDIENTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IngredientesRecord> getPrimaryKey() {
        return Keys.KEY_INGREDIENTES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IngredientesRecord>> getKeys() {
        return Arrays.<UniqueKey<IngredientesRecord>>asList(Keys.KEY_INGREDIENTES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<IngredientesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<IngredientesRecord, ?>>asList(Keys.FK_ING_RECEITA);
    }

    public Receitas receitas() {
        return new Receitas(this, Keys.FK_ING_RECEITA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ingredientes as(String alias) {
        return new Ingredientes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ingredientes as(Name alias) {
        return new Ingredientes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ingredientes rename(String name) {
        return new Ingredientes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ingredientes rename(Name name) {
        return new Ingredientes(name, null);
    }
}
