/*
 * This file is generated by jOOQ.
 */
package com.libertest.generatedsources.entity.tables;


import com.libertest.generatedsources.entity.DefaultSchema;
import com.libertest.generatedsources.entity.Indexes;
import com.libertest.generatedsources.entity.Keys;
import com.libertest.generatedsources.entity.tables.records.MetadadosRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Metadados extends TableImpl<MetadadosRecord> {

    private static final long serialVersionUID = 574317451;

    /**
     * The reference instance of <code>metadados</code>
     */
    public static final Metadados METADADOS = new Metadados();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MetadadosRecord> getRecordType() {
        return MetadadosRecord.class;
    }

    /**
     * The column <code>metadados.ID</code>.
     */
    public final TableField<MetadadosRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>metadados.NOME_RECEITA</code>.
     */
    public final TableField<MetadadosRecord, String> NOME_RECEITA = createField("NOME_RECEITA", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>metadados.TEMPO_PREP</code>.
     */
    public final TableField<MetadadosRecord, Integer> TEMPO_PREP = createField("TEMPO_PREP", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>metadados.REND_PORCAO</code>.
     */
    public final TableField<MetadadosRecord, Integer> REND_PORCAO = createField("REND_PORCAO", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>metadados.OBSERVACOES</code>.
     */
    public final TableField<MetadadosRecord, String> OBSERVACOES = createField("OBSERVACOES", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>metadados</code> table reference
     */
    public Metadados() {
        this(DSL.name("metadados"), null);
    }

    /**
     * Create an aliased <code>metadados</code> table reference
     */
    public Metadados(String alias) {
        this(DSL.name(alias), METADADOS);
    }

    /**
     * Create an aliased <code>metadados</code> table reference
     */
    public Metadados(Name alias) {
        this(alias, METADADOS);
    }

    private Metadados(Name alias, Table<MetadadosRecord> aliased) {
        this(alias, aliased, null);
    }

    private Metadados(Name alias, Table<MetadadosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Metadados(Table<O> child, ForeignKey<O, MetadadosRecord> key) {
        super(child, key, METADADOS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.METADADOS_FK_META_RECEITA, Indexes.METADADOS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MetadadosRecord, Integer> getIdentity() {
        return Keys.IDENTITY_METADADOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MetadadosRecord> getPrimaryKey() {
        return Keys.KEY_METADADOS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MetadadosRecord>> getKeys() {
        return Arrays.<UniqueKey<MetadadosRecord>>asList(Keys.KEY_METADADOS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MetadadosRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MetadadosRecord, ?>>asList(Keys.FK_META_RECEITA);
    }

    public Receitas receitas() {
        return new Receitas(this, Keys.FK_META_RECEITA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Metadados as(String alias) {
        return new Metadados(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Metadados as(Name alias) {
        return new Metadados(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Metadados rename(String name) {
        return new Metadados(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Metadados rename(Name name) {
        return new Metadados(name, null);
    }
}
