/*
 * This file is generated by jOOQ.
 */
package com.libertest.generatedsources.entity;


import com.libertest.generatedsources.entity.tables.Categorias;
import com.libertest.generatedsources.entity.tables.Ingredientes;
import com.libertest.generatedsources.entity.tables.Metadados;
import com.libertest.generatedsources.entity.tables.Receitas;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1124104863;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>categorias</code>.
     */
    public final Categorias CATEGORIAS = com.libertest.generatedsources.entity.tables.Categorias.CATEGORIAS;

    /**
     * The table <code>ingredientes</code>.
     */
    public final Ingredientes INGREDIENTES = com.libertest.generatedsources.entity.tables.Ingredientes.INGREDIENTES;

    /**
     * The table <code>metadados</code>.
     */
    public final Metadados METADADOS = com.libertest.generatedsources.entity.tables.Metadados.METADADOS;

    /**
     * The table <code>receitas</code>.
     */
    public final Receitas RECEITAS = com.libertest.generatedsources.entity.tables.Receitas.RECEITAS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Categorias.CATEGORIAS,
            Ingredientes.INGREDIENTES,
            Metadados.METADADOS,
            Receitas.RECEITAS);
    }
}
