/*
 * This file is generated by jOOQ.
 */
package com.libertest.generatedsources.entity;


import com.libertest.generatedsources.entity.tables.Categorias;
import com.libertest.generatedsources.entity.tables.Ingredientes;
import com.libertest.generatedsources.entity.tables.Metadados;
import com.libertest.generatedsources.entity.tables.Receitas;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CATEGORIAS_FK_CAT_RECEITA = Indexes0.CATEGORIAS_FK_CAT_RECEITA;
    public static final Index CATEGORIAS_PRIMARY = Indexes0.CATEGORIAS_PRIMARY;
    public static final Index INGREDIENTES_FK_ING_RECEITA = Indexes0.INGREDIENTES_FK_ING_RECEITA;
    public static final Index INGREDIENTES_PRIMARY = Indexes0.INGREDIENTES_PRIMARY;
    public static final Index METADADOS_FK_META_RECEITA = Indexes0.METADADOS_FK_META_RECEITA;
    public static final Index METADADOS_PRIMARY = Indexes0.METADADOS_PRIMARY;
    public static final Index RECEITAS_PRIMARY = Indexes0.RECEITAS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CATEGORIAS_FK_CAT_RECEITA = Internal.createIndex("FK_CAT_RECEITA", Categorias.CATEGORIAS, new OrderField[] { Categorias.CATEGORIAS.NOME_RECEITA }, false);
        public static Index CATEGORIAS_PRIMARY = Internal.createIndex("PRIMARY", Categorias.CATEGORIAS, new OrderField[] { Categorias.CATEGORIAS.ID }, true);
        public static Index INGREDIENTES_FK_ING_RECEITA = Internal.createIndex("FK_ING_RECEITA", Ingredientes.INGREDIENTES, new OrderField[] { Ingredientes.INGREDIENTES.NOME_RECEITA }, false);
        public static Index INGREDIENTES_PRIMARY = Internal.createIndex("PRIMARY", Ingredientes.INGREDIENTES, new OrderField[] { Ingredientes.INGREDIENTES.ID }, true);
        public static Index METADADOS_FK_META_RECEITA = Internal.createIndex("FK_META_RECEITA", Metadados.METADADOS, new OrderField[] { Metadados.METADADOS.NOME_RECEITA }, false);
        public static Index METADADOS_PRIMARY = Internal.createIndex("PRIMARY", Metadados.METADADOS, new OrderField[] { Metadados.METADADOS.ID }, true);
        public static Index RECEITAS_PRIMARY = Internal.createIndex("PRIMARY", Receitas.RECEITAS, new OrderField[] { Receitas.RECEITAS.NOME }, true);
    }
}
