/*
 * This file is generated by jOOQ.
 */
package com.libertest.generatedsources.entity;


import com.libertest.generatedsources.entity.tables.Categorias;
import com.libertest.generatedsources.entity.tables.Ingredientes;
import com.libertest.generatedsources.entity.tables.Metadados;
import com.libertest.generatedsources.entity.tables.Receitas;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>categorias</code>.
     */
    public static final Categorias CATEGORIAS = com.libertest.generatedsources.entity.tables.Categorias.CATEGORIAS;

    /**
     * The table <code>ingredientes</code>.
     */
    public static final Ingredientes INGREDIENTES = com.libertest.generatedsources.entity.tables.Ingredientes.INGREDIENTES;

    /**
     * The table <code>metadados</code>.
     */
    public static final Metadados METADADOS = com.libertest.generatedsources.entity.tables.Metadados.METADADOS;

    /**
     * The table <code>receitas</code>.
     */
    public static final Receitas RECEITAS = com.libertest.generatedsources.entity.tables.Receitas.RECEITAS;
}
