/*
 * This file is generated by jOOQ.
 */
package com.libertest.generatedsources.entity.tables.records;


import com.libertest.generatedsources.entity.tables.Metadados;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetadadosRecord extends UpdatableRecordImpl<MetadadosRecord> implements Record5<Integer, String, Integer, Integer, String> {

    private static final long serialVersionUID = -436758971;

    /**
     * Setter for <code>metadados.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>metadados.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>metadados.NOME_RECEITA</code>.
     */
    public void setNomeReceita(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>metadados.NOME_RECEITA</code>.
     */
    public String getNomeReceita() {
        return (String) get(1);
    }

    /**
     * Setter for <code>metadados.TEMPO_PREP</code>.
     */
    public void setTempoPrep(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>metadados.TEMPO_PREP</code>.
     */
    public Integer getTempoPrep() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>metadados.REND_PORCAO</code>.
     */
    public void setRendPorcao(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>metadados.REND_PORCAO</code>.
     */
    public Integer getRendPorcao() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>metadados.OBSERVACOES</code>.
     */
    public void setObservacoes(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>metadados.OBSERVACOES</code>.
     */
    public String getObservacoes() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Metadados.METADADOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Metadados.METADADOS.NOME_RECEITA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Metadados.METADADOS.TEMPO_PREP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Metadados.METADADOS.REND_PORCAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Metadados.METADADOS.OBSERVACOES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNomeReceita();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTempoPrep();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getRendPorcao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getObservacoes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomeReceita();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTempoPrep();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRendPorcao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getObservacoes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetadadosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetadadosRecord value2(String value) {
        setNomeReceita(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetadadosRecord value3(Integer value) {
        setTempoPrep(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetadadosRecord value4(Integer value) {
        setRendPorcao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetadadosRecord value5(String value) {
        setObservacoes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetadadosRecord values(Integer value1, String value2, Integer value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetadadosRecord
     */
    public MetadadosRecord() {
        super(Metadados.METADADOS);
    }

    /**
     * Create a detached, initialised MetadadosRecord
     */
    public MetadadosRecord(Integer id, String nomeReceita, Integer tempoPrep, Integer rendPorcao, String observacoes) {
        super(Metadados.METADADOS);

        set(0, id);
        set(1, nomeReceita);
        set(2, tempoPrep);
        set(3, rendPorcao);
        set(4, observacoes);
    }
}
